# Generated by Django 4.2.13 on 2024-05-24 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('tagline', models.TextField(blank=True, null=True)),
                ('runtime', models.IntegerField()),
                ('original_title', models.CharField(max_length=250)),
                ('original_language', models.TextField()),
                ('original_country', models.TextField()),
                ('overview', models.TextField(blank=True)),
                ('poster_path', models.TextField()),
                ('backdrop_path', models.TextField()),
                ('popularity', models.FloatField()),
                ('vote_average', models.FloatField()),
                ('vote_count', models.FloatField()),
                ('release_date', models.DateField()),
                ('trailer', models.URLField(blank=True, max_length=255, null=True)),
                ('director', models.TextField()),
                ('actors', models.TextField()),
                ('genres', models.ManyToManyField(to='movies.genre')),
                ('pick_users', models.ManyToManyField(related_name='picked_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('famous_line', models.TextField()),
                ('content', models.TextField()),
                ('watched_at', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_opened', models.BooleanField()),
                ('rating', models.FloatField()),
                ('like_users', models.ManyToManyField(blank=True, related_name='liked_reviews', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
